site:
  title: Tendroids Project Documentation
  url: https://qixotic-developers.github.io/fabric-tendroids
  start_page: tendroids::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: exts/qixotic.tendroids/docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
