[package]
# Semantic Versionning is used: https://semver.org/
version = "2.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Qixotic Software"]

# The title and description fields are primarly for displaying extension info in UI
title = "Qixotic Tendroids"
description = "Interactive cylinder-based wormlike sea creatures using Fabric/Warp/USDRT"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.adoc"

# Categories for UI
categories = ["Animation", "Warp", "Fabric"]

# Keywords for the extension
keywords = ["tendroid", "animation", "fabric", "creature", "procedural", "aquatic"]

# Location of change log file in target (final) folder of extension, relative to the root.
changelog = "docs/CHANGELOG.adoc"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
preview_image = "data/preview.png"
icon = "data/icon.png"

# We only depend on testing and Fabric extensions
[dependencies]
"omni.kit.uiapp" = {}
"omni.usd" = {}
"omni.ui" = {}
"usdrt.scenegraph" = {}
"omni.kit.pip_archive" = {}

# Main python module this extension provides, it will be publicly available as "import qixotic.tendroids".
[[python.module]]
name = "qixotic.tendroids"

[documentation]
pages = [
    "docs/README.adoc"
]
